# Generated by Django 3.1.1 on 2020-10-11 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_code', models.CharField(max_length=50)),
                ('p_name', models.CharField(max_length=200)),
                ('p_nutrition_grade_fr', models.CharField(max_length=1)),
                ('p_categories_tags', models.CharField(max_length=1000)),
                ('p_url', models.URLField()),
                ('p_image_url', models.URLField()),
                ('p_fat', models.FloatField(null=True)),
                ('p_salt', models.FloatField(null=True)),
                ('p_sugars', models.FloatField(null=True)),
                ('p_saturated_fat', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_date', models.DateTimeField(auto_now_add=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_and_sub.product')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
